"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ValidatorMiddleware = exports.addParamToRequest = exports.requestProcessor = exports.logger = exports.checkDocumentExists = exports.isAuthor = exports.authCheck = void 0;
const auth_middleware_1 = require("./auth.middleware");
exports.authCheck = auth_middleware_1.default;
const author_middleware_1 = require("./author.middleware");
exports.isAuthor = author_middleware_1.default;
const logger_middleware_1 = require("./logger.middleware");
Object.defineProperty(exports, "logger", { enumerable: true, get: function () { return logger_middleware_1.logger; } });
const request_middleware_1 = require("./request.middleware");
Object.defineProperty(exports, "requestProcessor", { enumerable: true, get: function () { return request_middleware_1.requestProcessor; } });
Object.defineProperty(exports, "addParamToRequest", { enumerable: true, get: function () { return request_middleware_1.addParamToRequest; } });
const validator_middleware_1 = require("./validator.middleware");
exports.ValidatorMiddleware = validator_middleware_1.default;
const document_exists_middleware_1 = require("./document.exists.middleware");
exports.checkDocumentExists = document_exists_middleware_1.default;
